<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-3BVFOOV" failures="1" tests="8" name="testngExample" time="0.138" errors="0" timestamp="2021-04-12T11:30:33 IST">
  <testcase classname="testng.AnnotationsExample" name="amethod4" time="0.009"/>
  <testcase classname="testng.SecondClass" name="secondClassMethod" time="0.006"/>
  <testcase classname="testng.AnnotationsExample" name="bmethod1" time="0.002"/>
  <testcase classname="testng.AnnotationsExample" name="method3" time="0.003"/>
  <testcase classname="testng.AnnotationsExample" name="signIn" time="0.002"/>
  <testcase classname="testng.AnnotationsExample" name="signIn" time="0.002"/>
  <testcase classname="testng.AnnotationsExample" name="signIn" time="0.002"/>
  <testcase classname="testng.AnnotationsExample" name="zmethod2" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng.AnnotationsExample.zmethod2(AnnotationsExample.java:84)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- zmethod2 -->
</testsuite> <!-- testngExample -->
